### ISSUE TITLE
remove_all_matching assumes it's being passed a single name but is frequently called with a list if names

### ISSUE THREAD

**Issue by graemerobertson** [jonhadfield/python-hosts#13]
For example, [here](https://github.com/jonhadfield/python-hosts/blob/7eddbb4e8bcac723a14092db87d69c94c56dd41a/python_hosts/hosts.py#L357) we call `remove_all_matching` with a list of names to match on. However, the `remove_all_matching` [implentation](https://github.com/jonhadfield/python-hosts/blob/7eddbb4e8bcac723a14092db87d69c94c56dd41a/python_hosts/hosts.py#L250) assumes it's being passed a single host name.

This means that, for example, when you try and add an entry for `127.0.0.1` with the force flag set, old entries for `127.0.0.1` don't get removed even though they should do.

**Comment by jonhadfield** [comment]
I've pushed a potential fix and some additional tests.
Could you try again with tag 0.3.9?
pip install https://github.com/jonhadfield/python-hosts/archive/0.3.9.zip

**Comment by graemerobertson** [comment]
Yep, seems good! :shipit:

**Comment by jonhadfield** [comment]
Shipped.
Thanks!
