### ISSUE TITLE
CLI?

### ISSUE THREAD

**Issue by blopker** [jonhadfield/python-hosts#17]
Hey, this is a nice project. Nice work!

Question: would you be interested in adding a CLI entrypoint? Basically just a way to use this package from the commandline for simple use cases. I was thinking an interface similar to https://github.com/lextoumbourou/goodhosts

I could put a PR together.

**Comment by jonhadfield** [comment]
Hi, thanks. I wrote a CLI that uses this some time back: https://github.com/jonhadfield/hostman but, for some reason, never linked to it from this project. PRs for any updates or improvements would be great as I've not made any in ages.
Alternatively, if you want to write your own that uses this library then I'd be happy to link to it from here.

**Comment by blopker** [comment]
Excellent! My Google-fu failed me.

I think the only request I have would be to update hostman with the latest python-hosts, but otherwise hostman looks great.

Thanks!

**Comment by jonhadfield** [comment]
Will do. Thanks.
