### ISSUE TITLE
cannot import name 'Hosts'

### ISSUE THREAD

**Issue by deadstar2011** [jonhadfield/python-hosts#23]
Hi, at 0.4.6 version had error with command:
from python_hosts import Hosts, HostsEntry

Error:"cannot import name Hosts"

At version 0.4.5 anythink work perfect

**Comment by jonhadfield** [comment]
Hi, sorry, due to a change/regression I need to explore further, for this release, you'll need:
```from python_hosts.hosts import Hosts, HostsEntry```
Sorry, I'll put out a 0.4.7 release later today.

**Comment by deadstar2011** [comment]
> Hi, sorry, due to a change/regression I need to explore further, for this release, you'll need:
> `from python_hosts.hosts import Hosts, HostsEntry`
> Sorry, I'll put out a 0.4.7 release later today.

**Comment by deadstar2011** [comment]
thanks, friend

**Comment by jonhadfield** [comment]
Fixed in 0.4.7
