### ISSUE TITLE
Verify against an object

### ISSUE THREAD

**Issue by bad-ip** [jonhadfield/python-hosts#3]
This is more or less a feature request. I'd like to be able to verify the existence of some hosts entries. I may go ahead and do a PR to implement this. I'm already doing this through putting each line into a hash and splitting it.

**Comment by jonhadfield** [comment]
Hi, couldn't you use the exists method? For example, load the existing host entries into an instance of hosts and then call hosts_instance.exists() for each?
The code isn't optimised for checking multiple entries but if you're not talking thousands then it shouldn't take long.

**Comment by bad-ip** [comment]
Hey Jon,

I should've updated this. I had posted this after a cursory look over the documentation, once I dove into the code I found that the functionality already existed. Sorry for the useless post! Thanks for the quick response.
