### ISSUE TITLE
1.0.4 breaking change hosts_path -> path

### ISSUE THREAD

**Issue by mattrussell-sonocent** [jonhadfield/python-hosts#48]
We had some code that uses `python-hosts` break on update to 1.0.4 because `Hosts.hosts_path` was renamed to `path` in https://github.com/jonhadfield/python-hosts/commit/fa0e8608e132fbf82b4c4184f01eb6d92720966d. Easy to fix once you know about it, but would it be worth adding `hosts_path` back for backwards compatibility?

**Comment by jonhadfield** [comment]
Sorry about that.  I should have incremented the minor version, rather than the patch, and made a note.   
Do you mean to revert the change, or also include `hosts_path` and somehow handle both? My issue with the latter is it would make it confusing wrt. setting, getting, and reprs, etc.
